
services:
  mysql_server:
    build:
      context: ./mysqldb
      dockerfile: Dockerfile
    restart: always
    environment:
      AUTHAPI_HOST: authapi
    networks:
      app_network:
        ipv4_address: 172.20.0.2
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  authapi:
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - "8010:8000"
    depends_on:
      mysql_server:
        condition: service_healthy
    volumes:
      - ./auth/AuthAPI:/app
    environment:
      SQL_HOST: mysql_server
      USER_API_HOST: userapi
      JOB_API_HOST: jobapi
    networks:
      app_network:
        ipv4_address: 172.20.0.3

  userapi:
    build:
      context: ./user
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    depends_on:
      mysql_server:
        condition: service_healthy
    volumes:
      - ./user/UserAPI:/app
    environment:
      SQL_HOST: mysql_server
      AUTH_API_HOST: authapi
      JOB_API_HOST: jobapi
    networks:
      app_network:
        ipv4_address: 172.20.0.4

  jobapi:
    build:
      context: ./job
      dockerfile: Dockerfile
    ports:
      - "8002:8000"
    depends_on:
      mysql_server:
        condition: service_healthy
    volumes:
      - ./job/JobAPI:/app
    environment:
      SQL_HOST: mysql_server
      AUTH_API_HOST: authapi
      USER_API_HOST: userapi
    networks:
      app_network:
        ipv4_address: 172.20.0.5
  utilsapi:
    build:
      context: ./utils
      dockerfile: Dockerfile
    ports:
      - "8003:8000"
    depends_on:
      mysql_server:
        condition: service_healthy
    volumes:
      - ./utils/UtilsAPI:/app
    networks:
      app_network:
        ipv4_address: 172.20.0.6


  modelapi:
    build:
      context: ./user
      dockerfile: Dockerfile
    ports:
      - "8004:8000"
    depends_on:
      - mysql_server
    volumes:
      - ./Model/ModelAPI:/app
    environment:
      SQL_HOST: mysql_server
      AUTH_API_HOST: authapi
      JOB_API_HOST: jobapi
    networks:
      app_network:
        ipv4_address: 172.20.0.7

networks:
  app_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

