import requests

# List of industries
industries = industries = [
    "Aerospace", "Agriculture", "Automotive", "Banking", "Biotechnology",
    "Construction", "Consulting", "Consumer Products", "Education", "Energy",
    "Entertainment", "Financial Services", "Food and Beverage", "Government",
    "Healthcare", "Hospitality", "Information Technology", "Insurance", "Law",
    "Logistics", "Manufacturing", "Marketing", "Media", "Mining", "Non-Profit",
    "Pharmaceuticals", "Real Estate", "Retail", "Sports", "Telecommunications",
    "Textiles", "Transportation", "Utilities", "Waste Management", "Accounting",
    "Advertising", "Aerospace and Defense", "Agribusiness", "Airlines",
    "Alternative Energy", "Animation", "Apparel", "Arms", "Architecture",
    "Art", "Artificial Intelligence", "Auctions", "Audio", "Auditing",
    "B2B", "B2C", "Beverages", "Biometrics", "Blockchain", "Bookkeeping",
    "Broadcasting", "Business Intelligence", "Catering", "Charity",
    "Chemicals", "Civil Engineering", "Cloud Computing", "Commercial Real Estate",
    "Commodities", "Computer Hardware", "Computer Software", "Construction Management",
    "Consulting Services", "Content Creation", "Corporate Finance", "Cybersecurity",
    "Data Analytics", "Data Mining", "Debt Collection", "Defence", "Design",
    "Digital Marketing", "Digital Media", "Distribution", "Drones", "E-commerce",
    "Economics", "Education Technology", "Electrical Engineering", "Electronics",
    "Embedded Systems", "Emergency Services", "Employment", "Engineering",
    "Environmental Services", "Event Management", "Facilities Management",
    "Fashion", "Film", "Financial Consulting", "Financial Technology", "Fishery",
    "Fitness", "Fleet Management", "Floristry", "Forestry", "Freight",
    "Funeral Services", "Gambling", "Gaming", "Gardening", "Gas", "Glass",
    "Graphic Design", "Green Energy", "Handicrafts", "Health and Safety",
    "Healthcare Technology", "Heating", "Home Automation", "Home Improvement",
    "Home Services", "Human Resources", "Hydropower", "Industrial Design",
    "Industrial Engineering", "Information Services", "Infrastructure",
    "Interior Design", "Internet", "Investment Banking", "Jewelry", "Journalism",
    "Laboratories", "Landscaping", "Legal Services", "Leisure", "Lending",
    "Libraries", "Life Sciences", "Lighting", "Linguistics", "Luxury Goods",
    "Machinery", "Management Consulting", "Manufacturing Engineering",
    "Marine Engineering", "Market Research", "Mass Media", "Material Science",
    "Mechanical Engineering", "Medical Devices", "Metalworking", "Microelectronics",
    "Military", "Mobile Apps", "Motion Pictures", "Multimedia", "Museums",
    "Music", "Nanotechnology", "Natural Resources", "Network Security",
    "Newspapers", "Nutrition", "Occupational Health", "Oil", "Online Services",
    "Optical Engineering", "Packaging", "Paper", "Patent Services",
    "Payment Processing", "Personal Finance", "Personal Services", "Pest Control",
    "Petroleum", "Philanthropy", "Photography", "Plastics", "Plumbing",
    "Podcasting", "Political Consulting", "Postal Services", "Printing",
    "Product Design", "Professional Services", "Project Management",
    "Property Management", "Public Relations", "Publishing", "Quality Assurance",
    "Railways", "Real Estate Development", "Recycling", "Regulatory Affairs",
    "Renewable Energy", "Research", "Resorts", "Restaurants", "Retail Banking",
    "Risk Management", "Robotics", "Safety", "Satellite", "Security",
    "Semiconductors", "Shipping", "Social Media", "Software Development",
    "Solar Energy", "Space", "Speech Recognition", "Sports Management",
    "Staffing", "Stock Exchange", "Storage", "Supply Chain Management",
    "Surveying", "Sustainability", "Talent Management", "Tax Services",
    "Telecommunications Equipment", "Textile Engineering", "Theatre",
    "Tobacco", "Tourism", "Trading", "Training", "Translation", "Travel",
    "Urban Planning", "Utilities Management", "Venture Capital", "Video Games",
    "Virtual Reality", "Waste Management", "Water Treatment", "Web Development",
    "Wholesale", "Wind Energy", "Wine", "Wireless", "Woodworking", "Writing",
    "Zoos", "3D Printing", "Advertising Technology", "Aeronautical Engineering",
    "Agricultural Equipment", "Agricultural Science", "Agricultural Technology",
    "Air Cargo", "Air Traffic Control", "Aircraft Leasing", "Airport Management",
    "Allied Health", "Alternative Medicine", "Animal Breeding", "Animal Health",
    "Animal Training", "Antique Dealing", "Applied Science", "Aquaculture",
    "Archaeology", "Arctic Exploration", "Arms Control", "Art Education",
    "Art Restoration", "Artificial Organs", "Astrobiology", "Astronomy",
    "Astrophysics", "Audio Engineering", "Audiology", "Aviation", "Bacteriology",
    "Banking Technology", "Biosciences", "Biomedical Engineering", "Biostatistics",
    "Botany", "Broadcast Engineering", "Building Services", "Business Analysis",
    "Business Process Outsourcing", "Call Centers", "Camerawork", "Canning",
    "Carbon Management", "Cardiology", "Carpentry", "Cartography", "Cattle Farming",
    "Cement Manufacturing", "Ceramics", "Charcoal Production", "Chemical Engineering",
    "Chiropractic", "Circuit Design", "City Planning", "Clinical Research",
    "Clothing Manufacturing", "Coal Mining", "Coastal Engineering", "Cognitive Science",
    "Cold Storage", "Commercial Banking", "Commercial Diving", "Commercial Fishing",
    "Commercial Lending", "Commodity Trading", "Community Development", "Commuter Rail",
    "Compounding Pharmacy", "Computational Biology", "Computational Linguistics",
    "Computer Animation", "Computer Forensics", "Computer Graphics", "Computer Networking",
    "Concrete Manufacturing", "Confectionery", "Conference Services", "Construction Equipment",
    "Construction Materials", "Consumer Electronics", "Consumer Finance", "Consumer Goods",
    "Consumer Health", "Consumer Research", "Container Shipping", "Contract Research",
    "Control Systems", "Conveyancing", "Corporate Banking", "Corporate Governance",
    "Corporate Security", "Cosmetics", "Cranes", "Credit Analysis", "Credit Reporting",
    "Credit Unions", "Cryogenics", "Cultural Heritage", "Customer Service", "Customs Brokerage",
    "Cutlery", "Dairy Farming", "Dairy Products", "Data Centers", "Data Recovery",
    "Debt Management", "Defense Technology", "Dental Equipment", "Dental Practices",
    "Design Engineering", "Desalination", "Diagnostic Services", "Die Casting",
    "Diesel Engines", "Digital Forensics", "Digital Printing", "Digital Transformation",
    "Direct Marketing", "Disaster Recovery", "Display Technology", "Distance Learning",
    "Diving Equipment", "Document Management", "Documentary Film", "Domestic Services",
    "Drafting", "Drainage", "Dyeing", "Earthmoving Equipment", "Ecology", "Economic Development",
    "Education Administration", "Electric Motors", "Electroplating", "Electrotherapy",
    "Embryology", "Emergency Medicine", "Emission Control", "Employee Benefits",
    "Employee Training", "Employment Law", "Energy Consulting", "Energy Distribution",
    "Energy Efficiency", "Energy Engineering", "Energy Research", "Energy Storage",
    "Engine Repair", "Engineering Consulting", "Engineering Design", "Engineering Services",
    "Engraving", "Entertainment Law", "Environmental Consulting", "Environmental Engineering",
    "Environmental Health", "Environmental Law", "Environmental Research", "Epidemiology",
    "Equine Science", "Equipment Rental", "Ergonomics", "Estate Management",
    "Ethical Hacking", "Ethnography", "Event Planning", "Event Security",
    "Executive Coaching", "Exhibition Services", "Exterminators", "Facilities Engineering",
    "Facilities Services", "Family Law", "Farm Equipment", "Farm Management",
    "Fashion Design", "Fashion Merchandising", "Feasibility Studies", "Feed Manufacturing",
    "Fiber Optics", "Field Services", "Film Distribution", "Film Production",
    "Filtration", "Financial Advisory", "Financial Analysis", "Financial Auditing",
    "Financial Planning", "Financial Reporting", "Fine Arts", "Fire Protection",
    "Fish Farming", "Fisheries", "Floriculture", "Flour Milling", "Fluid Dynamics",
    "FMCG", "Food Manufacturing", "Food Processing", "Food Safety", "Food Science",
    "Food Services", "Forestry Management", "Forging", "Foundry", "Freight Forwarding",
    "Fruit Production", "Fuel Cells", "Funeral Directing", "Furnace Manufacturing",
    "Furniture Design", "Furniture Manufacturing", "Futures Trading", "Gastroenterology",
    "Genealogy", "General Contracting", "Geodesy", "Geography", "Geoinformatics",
    "Geology", "Geophysics", "Geoscience", "Geriatrics", "Giftware", "Glass Manufacturing",
    "Gold Mining", "Golf Course Management", "Government Contracting", "Grain Milling",
    "Graphic Arts", "Graphite Mining", "Green Building", "Greenhouse Farming",
    "Ground Handling", "Gymnastics", "Gynecology", "Habilitation", "Hairdressing",
    "Handicapped Services", "Hardwood Products", "Haulage", "Health Clubs",
    "Health Economics", "Health Informatics", "Health Insurance", "Health Promotion",
    "Health Services", "Healthcare Consulting", "Healthcare Engineering",
    "Healthcare Management", "Heavy Equipment", "Helicopter Services", "Hematology",
    "Herb Farming", "Herbal Medicine", "Higher Education", "Highway Engineering",
    "Histology", "Historical Research", "Holography", "Home Care", "Home Health",
    "Home Inspections", "Home Security", "Homeopathy", "Horse Breeding", "Horse Racing",
    "Horticulture", "Hospital Administration", "Hospital Equipment", "Hotel Management",
    "Housekeeping", "Human Factors", "Hydraulic Engineering", "Hydraulics",
    "Hydrography", "Hydrology", "Hygiene", "Hyperbaric Medicine", "Ice Cream Manufacturing",
    "Illustration", "Immigration Law", "Import/Export", "Industrial Automation",
    "Industrial Design Engineering", "Industrial Hygiene", "Industrial Machinery",
    "Industrial Safety", "Industrial Services", "Industrial Supplies",
    "Industrial Waste Management", "Information Management", "Infrastructure Engineering",
    "Injection Molding", "Innkeeping", "Inorganic Chemistry", "Insolvency",
    "Inspection Services", "Installation Services", "Instructional Design",
    "Instrument Engineering", "Instrumentation", "Insurance Adjusting", "Insurance Brokerage",
    "Insurance Law", "Insurance Services", "Interior Architecture", "Internet Marketing",
    "Interpretation Services", "Investment Management", "Iron and Steel",
    "Irrigation", "IT Services", "Jute Products", "Juvenile Services", "Labor Law",
    "Laboratory Equipment", "Laboratory Services", "Lactation Consulting", "Land Management",
    "Land Surveying", "Landscaping Architecture", "Language Services", "Laser Technology",
    "Lathe Manufacturing", "Laundry Services", "Law Enforcement", "Lead Generation",
    "Leadership Development", "Leather Goods", "Legal Consulting", "Leisure Services",
    "Library Science", "Lifeguard Services", "Lighting Design", "Lighting Services",
    "Lime Manufacturing", "Line Maintenance", "Livestock", "Lobbying", "Locksmithing",
    "Log Home Manufacturing", "Logging", "Logistics Consulting", "Lumber", "Machining",
    "Magnetics", "Mail Order", "Maintenance Engineering", "Makeup Artistry",
    "Marine Biology", "Marine Surveying", "Market Analysis", "Marketing Research",
    "Materials Engineering", "Materials Management", "Mathematics", "Mechanical Design",
    "Mechanical Engineering Consulting", "Mechanical Testing", "Medical Billing",
    "Medical Coding", "Medical Equipment Rental", "Medical Imaging", "Medical Research",
    "Medical Testing", "Medico-Legal Services", "Mental Health Services", "Meteorology",
    "Metrology", "Microbiology", "Microfabrication", "Microfinance", "Micromachining",
    "Microscopy", "Midwifery", "Millinery", "Mining Engineering", "Mining Equipment",
    "Missionary Work", "Mixed Farming", "Mobile Marketing", "Mobile Payment",
    "Mobile Phone Retailing", "Mobile Phone Services", "Modelling Agencies",
    "Molecular Biology", "Molecular Diagnostics", "Monetary Policy", "Mortgage Brokerage",
    "Mortgage Lending", "Motion Capture", "Motion Graphics", "Motorsport",
    "Mountaineering", "Multicultural Marketing", "Multifamily Housing", "Multimedia Services",
    "Municipal Services", "Mushroom Farming", "Music Publishing", "Music Therapy",
    "Mutual Funds", "Nanomaterials", "Natural Disasters", "Natural Gas",
    "Natural Medicine", "Naval Architecture", "Navigation", "Network Administration",
    "Network Engineering", "Network Infrastructure", "Network Management",
    "Neuroscience", "New Media", "Non-Destructive Testing", "Non-Ferrous Metals",
    "Non-Governmental Organizations", "Non-Profit Consulting", "Nonwoven Fabrics",
    "Nuclear Engineering", "Nuclear Medicine", "Nuclear Physics", "Nursing Homes",
    "Nutraceuticals", "Nutrition Consulting", "Occupational Therapy", "Ocean Engineering",
    "Oceanography", "Office Furniture", "Offshore Engineering", "Oil and Gas",
    "Oilfield Services", "Oncology", "Online Advertising", "Online Banking",
    "Online Publishing", "Operating Systems", "Operations Consulting", "Ophthalmology",
    "Optometry", "Oral and Maxillofacial Surgery", "Oral Hygiene", "Organic Farming",
    "Organic Products", "Organizational Development", "Ornamental Horticulture",
    "Orthodontics", "Orthopaedics", "Osteopathy", "Outdoor Advertising", "Outdoor Education",
    "Outplacement", "Outsourcing", "Overhead Cranes", "Packaging Engineering",
    "Packaging Services", "Palliative Care", "Paper Engineering", "Paralegal Services",
    "Paramedicine", "Parking Management", "Parole Services", "Patent Law",
    "Pathology", "Pavement Engineering", "Payroll Services", "Pediatric Dentistry",
    "Pediatrics", "Penology", "People Analytics", "Perfume", "Performance Marketing",
    "Performance Testing", "Periodontics", "Pest Control Consulting", "Pet Care",
    "Pet Grooming", "Pet Products", "Pet Services", "Petroleum Engineering",
    "Pharmaceutical Chemistry", "Pharmaceutical Engineering", "Pharmaceutical Manufacturing",
    "Pharmacy Consulting", "Phlebotomy", "Photocopiers", "Photofinishing",
    "Physical Education", "Physical Medicine", "Physical Rehabilitation", "Physics",
    "Piano Tuning", "Pipeline Engineering", "Plastic Surgery", "Plastics Engineering",
    "Plating", "Plumbing Consulting", "Pneumatics", "Podcast Consulting", "Podology",
    "Police Equipment", "Policy Analysis", "Political Campaigns", "Pollution Control",
    "Polymer Chemistry", "Polymer Engineering", "Pool Maintenance", "Poultry Farming",
    "Power Engineering", "Power Generation", "Power Tools", "Precious Metals",
    "Prepress Services", "Prescription Eyewear", "Presentation Training", "Preservation",
    "Primary Education", "Printing Services", "Private Equity", "Private Investigation",
    "Probate Law", "Process Engineering", "Procurement Consulting", "Product Distribution",
    "Product Engineering", "Product Inspection", "Product Management", "Product Safety",
    "Product Testing", "Professional Development", "Professional Services Consulting",
    "Project Engineering", "Project Funding", "Project Planning", "Property Development",
    "Property Law", "Property Services", "Psychiatry", "Psychology", "Public Affairs",
    "Public Finance", "Public Health", "Public Housing", "Public Law", "Public Policy",
    "Public Safety", "Public Speaking", "Public Transport", "Publishing Consulting",
    "Pump Manufacturing", "Quality Control", "Quantity Surveying", "Quarrying",
    "Radiation Protection", "Radiation Therapy", "Radiography", "Radiology",
    "Railroad Construction", "Railroad Equipment", "Ranching", "Rare Earth Metals",
    "Real Estate Appraisal", "Real Estate Consulting", "Recreational Vehicles",
    "Recycling Consulting", "Refining", "Reforestation", "Refurbishing", "Rehabilitation",
    "Reinsurance", "Religion", "Relocation Services", "Remediation", "Renewable Resources",
    "Research and Development", "Residential Construction", "Residential Services",
    "Resin Manufacturing", "Resource Management", "Restaurant Consulting", "Retail Consulting",
    "Retail Technology", "Retirement Homes", "Risk Analysis", "Risk Consulting",
    "Risk Management Consulting", "Road Construction", "Road Maintenance",
    "Road Transport", "Robotics Consulting", "Roofing", "Safety Consulting", "Sailing",
    "Sales Consulting", "Sales Training", "Sanitation Services", "Satellite Communications",
    "Satellite Navigation", "School Administration", "Science Education",
    "Scientific Consulting", "Scrap Metal", "Screen Printing", "Scriptwriting",
    "Seafood", "Search Engine Optimization", "Security Consulting", "Seed Production",
    "Self-Storage", "Semiconductor Consulting", "Sewage Treatment", "Shipbuilding",
    "Shipping and Handling", "Sign Manufacturing", "Silicon", "Simulation",
    "Site Preparation", "Skin Care", "Small Business Consulting", "Smartphone Apps",
    "Social Enterprise", "Social Research", "Social Services", "Software Consulting",
    "Software Engineering", "Software Sales", "Solar Technology", "Sound Engineering",
    "Special Education", "Speech and Language Therapy", "Sports Coaching",
    "Sports Consulting", "Sports Engineering", "Sports Science", "Stainless Steel",
    "Steel Construction", "Stock Photography", "Storage Solutions", "Strategic Consulting",
    "Structural Engineering", "Subsea Engineering", "Supply Chain Engineering",
    "Surgical Equipment", "Surveying Services", "Sustainable Agriculture",
    "Swimwear", "Synthetic Materials", "System Integration", "Systems Engineering",
    "Talent Acquisition", "Talent Development", "Talent Management Consulting",
    "Tax Consulting", "Tax Law", "Tax Preparation", "Taxation", "Technology Consulting",
    "Telecommunications Consulting", "Telecommunications Law", "Telematics",
    "Telemedicine", "Tennis Coaching", "Textile Consulting", "Theatre Consulting",
    "Theme Park Management", "Thermal Engineering", "Thermodynamics", "Tile Manufacturing",
    "Timber", "Timeshare", "Tobacco Products", "Tool Manufacturing", "Tourism Consulting",
    "Towing", "Trade Law", "Trade Shows", "Trading Consulting", "Training Consulting",
    "Translation Services", "Transmission", "Transportation Consulting", "Travel Consulting",
    "Travel Writing", "Trucking", "Trust Law", "Tutoring", "TV Broadcasting",
    "Tyre Manufacturing", "Underwater Welding", "Uniform Services", "Urban Development",
    "Utility Engineering", "Valve Manufacturing", "Vehicle Manufacturing", "Vending",
    "Veterinary Services", "Video Consulting", "Video Production", "Virtual Events",
    "Virtual Training", "Vision Care", "Visual Effects", "Voice Recognition",
    "Vocational Education", "Volunteer Services", "Waste Consulting", "Waste Disposal",
    "Water Engineering", "Water Management", "Water Sports", "Water Treatment Consulting",
    "Wealth Management", "Web Analytics", "Web Design", "Web Hosting", "Web Marketing",
    "Web Programming", "Web Security", "Webinar Services", "Wedding Planning",
    "Wellness Consulting", "Wind Power", "Wireless Consulting", "Wood Products",
    "Workforce Development", "Workforce Training", "Writing Consulting",
    "Youth Services", "Zoological Services"
]


# API endpoint
url = "http://localhost:8003/api/v1/industry/"

# Send each industry to the API
for industry in industries:
    response = requests.post(url, json={"industry": industry})
    if response.status_code == 200:
        print(f"Successfully added {industry}")
    else:
        print(f"Failed to add {industry}: {response.text}")
